export const haqCopy = {
  profile: {
    eyebrow: "Haq",
    heading: "Tell us about your household",
    description:
      "The first ten questions mirror UMANG's eligibility finder. The rest let the rule engine order what matters. Every answer is optional and self-declared.",
    browserNote:
      "This prototype stores your answers in this browser only.",
    progress: (current: number, total: number) =>
      `Question ${current} of ${total}`,
    skip: "Skip this question",
    continue: "Continue",
    finish: "See what may apply",
    error: "We could not save these answers. Try again.",
    preferNot: "Prefer not to say",
    question: {
      name: "What name should we use for this synthetic profile?",
      aadhaarLast4:
        "What are the last four digits of the synthetic Aadhaar number?",
      dob: "What is your date of birth?",
      gender: "How do you describe your gender?",
      currentState: "Which state or union territory do you live in now?",
      currentDistrict: "Which district do you live in now?",
      homeState: "Which state or union territory is your home state?",
      homeDistrict: "Which district is your home district?",
      incomeBand: "Which household income band do you declare?",
      employment: "What is your employment type?",
      marital: "What is your marital status?",
      isSingleParent: "Are you a single parent?",
      childrenAges: "How old are the children in your household?",
      parentsAges: "How old are your parents?",
      category: "Which category do you declare?",
      hasDisability: "Do you declare a disability?",
      housing: "What type of housing do you live in?",
      bpl: "Do you declare that you belong to the BPL category?",
      isSeniorCitizen: "Do you declare that you are a senior citizen?",
      residenceArea: "Do you live in an urban or rural area?",
      occupation: "Which occupation best describes you?",
      employmentStatus: "What is your current employment status?",
      minority: "Do you declare that you belong to a minority community?",
    },
    controls: {
      addChild: "Add another child",
      addParent: "Add another parent",
      remove: "Remove",
      noChildren: "No children in the household",
      noParents: "No parents to add",
      age: "Age",
    },
    options: {
      gender: [
        { label: "Woman", value: "F" },
        { label: "Prefer not to say", value: "NA" },
        { label: "Man", value: "M" },
        { label: "Transgender", value: "T" },
      ],
      category: [
        { label: "General", value: "general" },
        { label: "Other Backward Class", value: "obc" },
        { label: "Prefer not to say", value: "NA" },
        { label: "Particularly Vulnerable Tribal Group", value: "pvtg" },
        { label: "Scheduled Caste", value: "sc" },
        { label: "Scheduled Tribe", value: "st" },
      ],
      incomeBand: [
        { label: "Below 1 lakh", value: "<1L" },
        { label: "1 to 3 lakh", value: "1-3L" },
        { label: "Prefer not to say", value: "NA" },
        { label: "3 to 5 lakh", value: "3-5L" },
        { label: "5 to 8 lakh", value: "5-8L" },
        { label: "Above 8 lakh", value: "8L+" },
      ],
      disability: [
        { label: "Yes", value: "yes" },
        { label: "Prefer not to say", value: "NA" },
        { label: "No", value: "no" },
      ],
      employment: [
        { label: "Salaried", value: "salaried" },
        { label: "Gig work", value: "gig" },
        { label: "Self-employed", value: "self" },
        { label: "Unorganised work", value: "unorganised" },
        { label: "Student", value: "student" },
        { label: "Not employed", value: "none" },
      ],
      marital: [
        { label: "Single", value: "single" },
        { label: "Married", value: "married" },
        { label: "Prefer not to say", value: "NA" },
        { label: "Widowed", value: "widowed" },
        { label: "Separated", value: "separated" },
      ],
      yesNo: [
        { label: "Yes", value: "yes" },
        { label: "Prefer not to say", value: "NA" },
        { label: "No", value: "no" },
      ],
      residenceArea: [
        { label: "Urban", value: "urban" },
        { label: "Prefer not to say", value: "NA" },
        { label: "Rural", value: "rural" },
      ],
      occupation: [
        { label: "Student", value: "student" },
        { label: "Homemaker", value: "homemaker" },
        { label: "Prefer not to say", value: "NA" },
        { label: "Farmer", value: "farmer" },
        { label: "Wage worker", value: "wage-worker" },
        { label: "Professional", value: "professional" },
        { label: "Business owner", value: "business" },
        { label: "Retired", value: "retired" },
        { label: "Other", value: "other" },
      ],
      employmentStatus: [
        { label: "Employed", value: "employed" },
        { label: "Self-employed", value: "self-employed" },
        { label: "Prefer not to say", value: "NA" },
        { label: "Unemployed", value: "unemployed" },
        { label: "Student", value: "student" },
        { label: "Retired", value: "retired" },
      ],
      housing: [
        { label: "Own home", value: "own" },
        { label: "Registered rental", value: "rent-registered" },
        { label: "Prefer not to say", value: "NA" },
        { label: "Stamp-paper rental", value: "rent-stamp" },
        { label: "Employer housing", value: "employer" },
        { label: "With family", value: "family" },
      ],
    },
  },
  results: {
    eyebrow: "Haq results",
    heading: "What may apply to you",
    description:
      "These are possible matches from the facts you chose to share. The rules decide what appears; this prototype does not decide whether you qualify.",
    section: {
      overdue: "This should already have happened",
      available: "You may be entitled to this",
      upcoming: "Coming up for you",
    },
    empty: "No items in this section from the answers you shared.",
    cardFrame: "You may be entitled to this",
    why: "Why this appears",
    rule: "What the rule says",
    gives: "What it gives",
    how: "How to get it",
    authority: "Authority",
    hidden: (count: number, fields: number) =>
      `${count} more may apply. Answer ${fields} more ${fields === 1 ? "question" : "questions"} to see them.`,
    edit: "Edit your answers",
    comparison: {
      label: "Compare result views",
      current: "How this looks on UMANG today",
      yours: "Your list",
      legacyEyebrow: "Eligibility is not an answer",
      legacyHeading: "770 possible schemes",
      legacyDescription:
        "The observed UMANG flow asks for the same ten declared facts, then asks you to choose a category before it shows a browse list.",
      categoryPrompt: "Choose one or more categories to view",
      observedNote:
        "Observed on UMANG in August 2026. This count is shown for comparison and is not recalculated by this prototype.",
      selected: (count: number) =>
        count === 0
          ? "No category selected"
          : `${count} ${count === 1 ? "category" : "categories"} selected`,
      categories: [
        { label: "Social welfare and empowerment", count: 22 },
        { label: "Skills and employment", count: 14 },
        { label: "Banking and financial services", count: 12 },
        { label: "Education and learning", count: 11 },
        { label: "Health and wellness", count: 8 },
        { label: "Business and entrepreneurship", count: 7 },
        { label: "Utility and sanitation", count: 7 },
        { label: "Women and child", count: 7 },
        { label: "Agriculture, rural and environment", count: 6 },
        { label: "Science, IT and communications", count: 4 },
        { label: "Housing and shelter", count: 3 },
        { label: "Transport and infrastructure", count: 3 },
        { label: "Sports and culture", count: 2 },
      ],
    },
  },
  api: {
    invalid: "The request is not valid.",
  },
  facts: {
    gender: {
      F: "You told us you are a woman.",
      M: "You told us you are a man.",
      O: "You told us you use another description for your gender.",
      T: "You told us you are transgender.",
    },
    category: {
      general: "You told us you selected General.",
      obc: "You told us you selected Other Backward Class.",
      sc: "You told us you selected Scheduled Caste.",
      st: "You told us you selected Scheduled Tribe.",
      pvtg:
        "You told us you selected Particularly Vulnerable Tribal Group.",
    },
    childrenOne: (age: number) =>
      `You told us there is a child aged ${age} in your household.`,
    childrenMany: (ages: string) =>
      `You told us there are children aged ${ages} in your household.`,
  },
} as const;
