export const rtiCopy = {
  common: {
    back: "Back",
    continue: "Continue",
    loading: "Working",
    error: "Something went wrong. You can continue with your own text.",
  },
  describe: {
    eyebrow: "File an RTI request",
    heading: "What do you want to know?",
    intro: "Describe the problem in your own words. We will show you what we understood before anything is used.",
    placeholder: "For example: my father's pension application has been pending for eight months at the Karnataka treasury.",
    templatesHeading: "Or start from a common situation",
    templatesNote: "These are starting points, not fixed options. Pick the closest one and edit it until it describes your situation.",
    templates: [
      { label: "Pension pending", text: "My pension application has been pending for eight months and I have had no reply from the office." },
      { label: "Answer sheet and evaluation", text: "I want copies of my university answer sheet and the evaluation record for my examination." },
      { label: "Railway ticket refund", text: "My railway ticket refund has not arrived even though the train was cancelled." },
      { label: "Scholarship not credited", text: "My scholarship has not been credited to my account for this academic year." },
      { label: "FIR status", text: "I want to know the current status of the FIR I filed and what action has been taken on it." },
      { label: "Ward or municipal funds", text: "I want the records of how the ward development funds in my area were spent last year." },
      { label: "Passport application", text: "My passport application has not moved past police verification and I want the file status." },
      { label: "EPF claim status", text: "My provident fund claim has been pending and I want the records showing its current status." },
    ],
    submitAction: "Show what you understood",
    confirmation: "What we understood",
    subject: "Subject",
    original: "Your original words",
    youSaid: "You said",
    wantsAction: "What are you hoping for?",
    records: "Copies of documents, files or records",
    status: "To find out what stage something is at",
    actionOption: "For someone to actually do something",
    lifeLiberty: "Does this concern someone's life or liberty?",
    bpl: "Is your household below the poverty line?",
    yes: "Yes",
    no: "No",
    preferNot: "Prefer not to say",
    confirm: "Yes, this is right",
  },
  jurisdiction: {
    eyebrow: "Jurisdiction check",
    heading: "Which government holds the records?",
    bodyLevel: "Which government does this concern?",
    central: "Central government",
    state: "State government",
    unknown: "I am not sure",
    stateLabel: "Which state is this about?",
    statePlaceholder: "Select a state or union territory",
    statesGroup: "States",
    unionTerritoriesGroup: "Union territories",
    helper: "Central means a ministry, a central department, a public sector bank, EPFO, Indian Railways, a central university. State means municipality, state police, state schools, land records, state transport, state pensions.",
    draftAnyway: "Draft it anyway",
    resolveFirst: "Choose central or state before simulated submission.",
  },
  authority: {
    eyebrow: "Authority and officer",
    heading: "Send it to the right public authority",
    reasoning: (matchedTerm: string, authority: string) =>
      `You mentioned "${matchedTerm}", so this goes to the ${authority}.`,
    reasoningManual: (authority: string) =>
      `You chose the ${authority}. We did not pick this, so check it against the directory before filing.`,
    searchLabel: "Search the authored directory",
    searchHint: "Type to filter, or type your own if nothing here fits.",
    searchPlaceholder: "Start typing, for example pension or provident fund",
    holdsHeading: "What this authority holds",
    officerNoteHeading: "Which office to address",
    termsHeading: "Search terms that point here",
    noMatch: "No authored entry matches what you typed. That is fine. Enter the authority yourself below and check the government directory first.",
    unknown: "We could not work out which authority this belongs to. The government's own directory of Public Information Officers is at rti.gov.in. Search there, then come back and enter it.",
    name: "Public authority",
    officer: "Officer title",
    directory: "The officer directory is on rti.gov.in. Filing happens on rtionline.gov.in. They are different sites.",
    transfer: "A wrongly addressed application should be transferred within five days under Section 6(3), but that transfer is not guaranteed.",
  },
  draft: {
    eyebrow: "Rewrite",
    heading: "Make the request harder to refuse",
    original: "What you wrote",
    rewritten: "What we will file",
    changes: "What changed and why",
    count: (count: number) => `${count.toLocaleString("en-IN")} of 3,000 characters`,
    action: "Check this request",
    fallbackTitle: "Your wording is preserved",
    fallbackReason: "The rewriting service is unavailable, so nothing was changed. You can edit the filing text yourself.",
  },
  checks: {
    eyebrow: "Pre-flight",
    heading: "Check it before submission",
    intro: "Every check comes from the authored RTI rule pack.",
    pass: "Pass",
    warn: "Warning",
    block: "Blocks submission",
    consequence: "What can happen",
    fix: "How to fix it",
    singleSubject: "This application contains one subject and one authority.",
    asksForRecords: "The text asks for records, not reasons or opinions.",
    identity: "An Aadhaar, PAN or other identity document is attached.",
    attachment: "Optional PDF attachment",
    bpl: "A valid BPL certificate is attached.",
    submit: "Continue to simulated submission",
    download: "Download the application",
    blocked: "Resolve every blocking check before simulated submission.",
    resolve: "Resolve the government type first",
  },
  submit: {
    eyebrow: "Simulated submission",
    heading: "Practice the submission safely",
    label: "Simulation only. No government portal, payment gateway or email service is contacted.",
    emailStep: "1. Email and OTP",
    email: "Email address",
    emailPlaceholder: "you@example.com",
    sendOtp: "Show simulated OTP",
    otpPanel: "Simulated OTP: 4471. In the real portal this arrives by email.",
    otp: "Enter the simulated OTP",
    verify: "Verify simulated OTP",
    wrongOtp: "Enter 4471 to continue.",
    identityStep: "2. Contact details",
    identityLabel: "Simulated step. These fields exist to show what the real portal asks for. Use synthetic values only.",
    mobile: "Mobile number, synthetic",
    mobilePlaceholder: "10 digits",
    mobileNote: "The real portal collects a mobile number for SMS alerts. Do not enter a real number here.",
    mobileInvalid: "Enter 10 digits. Any synthetic value is fine.",
    useSynthetic: "Fill a synthetic number",
    aadhaar: "Aadhaar number, optional and synthetic",
    aadhaarWarning: "Section 6(2) does not require you to prove who you are, and you should not attach an identity document to a real application. This field is here only to show what the real portal puts in front of you.",
    aadhaarNote: "Any number entered here must fail the Aadhaar checksum, so a real number cannot be stored.",
    aadhaarRejected: "That number satisfies the Aadhaar checksum, so it could be a real one. It has not been kept. Use the synthetic number instead.",
    aadhaarAccepted: "Accepted. This number fails the Aadhaar checksum, so it is not a real Aadhaar.",
    identityContinue: "Continue",
    feeStep: "3. Fee",
    feePaid: "The statutory application fee is ₹10.",
    feeBpl: "There is no application fee when a valid BPL certificate is attached.",
    paymentNote: "Simulated payment only. There are no card fields and no real gateway.",
    pay: "Complete simulated payment",
    registrationStep: "4. Registration",
    registration: "DOPTR/E/2026/04417",
    registrationLabel: "Simulated registration number in the real format",
    warning: "If the real portal takes payment but issues no number, wait 24 to 48 hours. Do not pay again.",
    create: "Open your case",
  },
  tracker: {
    eyebrow: "Your case",
    heading: "The legal clock is visible",
    elapsed: "Elapsed",
    remaining: "Remaining",
    days: "days",
    hours: "hours",
    unit: (value: number, lifeLiberty: boolean) =>
      lifeLiberty
        ? (value === 1 ? "hour" : "hours")
        : (value === 1 ? "day" : "days"),
    ordinaryReason: "The standard 30-day reply period applies.",
    libertyReason: "Life or liberty was marked yes, so the 48-hour reply period applies.",
    next: "See what happens next",
    nextNote: "This advances simulated time. No department is contacted.",
    fired: "Silence has become a deemed refusal. First Appeal is now unlocked.",
    overdue: "Overdue by",
    lapsedClockLabel: "Reply overdue",
    lapsedConsequence: (consequence: string) =>
      `The reply period has run out, so ${consequence}.`,
    occurred: "Occurred",
    windowClosed: "Window closed",
    facts: {
      heading: "Your filed request",
      registration: "Registration number",
      authority: "Public authority",
      officer: "Officer addressed",
      requestHeading: "The request as filed",
      requestNote: "Rewritten to ask for records rather than reasons, so it cannot be refused for asking a question.",
      original: "What you first wrote",
    },
    current: "Happening now",
    lapsed: {
      eyebrow: "Deemed refusal",
      heading: "They did not reply. File your First Appeal.",
      action: "File the First Appeal",
      filedHeading: "Your First Appeal is with the Appellate Authority.",
      filedBody:
        "The Authority has its own deadline now. Second Appeal opens once that deadline is decided or runs out.",
      filedAction: "Open your First Appeal",
      deadline: (label: string, days: number) => `${label}: ${days} days`,
    },
    advanceBlocked:
      "Time moves again once the First Appeal is filed. The next deadline belongs to the Appellate Authority, not to the officer who stayed silent.",
    planCode: "Case code",
    locked: "Locked until",
    source: "Source",
    status: "Status",
    statuses: {
      none: "Not started",
      applied: "Applied",
      stuck: "Stuck",
      done: "Complete",
    },
    jobs: {
      DO: "DO",
      WAIT: "WAIT",
      CLAIM: "CLAIM",
      PROTECT: "PROTECT",
      ESCALATE: "ESCALATE",
    },
    buckets: {
      before: "Before filing",
      now: "Current",
      next: "Next",
      later: "Later",
    },
    flow: {
      eyebrow: "Live case map",
      heading: "Where your request is now",
      title: "Your Right to Information case process",
      description: "A live diagram showing the request, reply or no reply, appeals, transfer and Section 18 complaint routes.",
      request: "RTI REQUEST",
      transfer: "TRANSFER",
      reply: "REPLY",
      noReply: "NO REPLY",
      first: "FIRST APPEAL",
      decision: "DECISION",
      noDecision: "NO DECISION",
      second: "SECOND APPEAL",
      complaint: ["SECTION 18", "COMPLAINT"],
      withinFive: "within 5 days",
      again: (wait: string) => `${wait} again`,
      unsatisfactory: "if unsatisfactory, 30 days",
      fileFirst: "30 days to file",
      withinFortyFive: "within 45 days",
      afterFortyFive: "after 45 days",
      withinNinety: "within 90 days",
      noLimit: "no time limit",
      caption: "This is the same process the government publishes as a diagram. We made it move.",
      states: {
        complete: "Done",
        current: "Now",
        available: "Open to you",
        locked: "Not open yet",
      },
      parallel: "Parallel route",
      outcome: "One of two outcomes",
      open: "Open",
    },
  },
  detail: {
    back: "Back to your case",
    authority: "Authority",
    expect: "What to expect",
    basis: "Statutory basis",
    status: "Update status",
    save: "Save status",
    source: "Open the primary source",
    missing: "This step is not part of the case.",
  },
  appeals: {
    first: {
      eyebrow: "First Appeal",
      heading: "Challenge the silence",
      intro: "A First Appeal asks an officer senior to the Public Information Officer to review what happened.",
      draftHeading: "Your drafted First Appeal",
      submit: "Submit the simulated First Appeal",
      submitted: "First Appeal submitted in this simulation",
      complete: "See the appeal decision arrive",
      clock: "Decision clock",
      clockReason: "The First Appellate Authority has up to 45 days to decide.",
    },
    second: {
      eyebrow: "Second Appeal",
      heading: "Take the case to the Commission",
      intro: "A Second Appeal goes to the Information Commission after the First Appeal route has been completed.",
      draftHeading: "Your drafted Second Appeal",
      submit: "Submit the simulated Second Appeal",
      submitted: "Second Appeal submitted in this simulation",
    },
    complaint: {
      eyebrow: "Section 18 complaint",
      heading: "Challenge the officer's conduct",
      intro: "An appeal challenges the decision. A complaint challenges the officer's conduct. This is a parallel route from the original request.",
      submit: "Lodge the simulated complaint",
      submitted: "Section 18 complaint lodged in this simulation",
      noLimit: "No time limit",
    },
    locked: "This route is locked",
    lockedUntil: "It opens when this step is complete:",
    originalRegistration: "Original registration number",
    statutoryFacts: "What the law says",
    draftLabel: "Editable draft",
    simulation: "Simulation only. Nothing is sent to an authority or commission.",
    daysElapsed: "days elapsed",
    daysRemaining: "days remaining",
    back: "Back to your case",
    source: "Open the primary source",
  },
  api: {
    invalid: "The request is not valid.",
    notFound: "This case was not found in this browser.",
    unavailable: "The writing service is unavailable.",
  },
} as const;
