import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export interface ApplicationPdfInput {
  authorityName: string;
  officer: string;
  ministry?: string;
  body: string;
  registrationNumber?: string;
  /** ISO date. Passed in so the document is reproducible in tests. */
  date: string;
  simulated: boolean;
}

const PAGE = { width: 595.28, height: 841.89 }; // A4 in points
const MARGIN = 56;
const BODY_SIZE = 11;
const LINE = 16;

/**
 * Wraps text to the available width using the font's real metrics, rather than
 * guessing at a character count, so long authority names do not overrun.
 */
function wrap(
  text: string,
  font: { widthOfTextAtSize(t: string, s: number): number },
  size: number,
  maxWidth: number,
): string[] {
  const lines: string[] = [];
  for (const paragraph of text.split(/\n/)) {
    if (!paragraph.trim()) {
      lines.push("");
      continue;
    }
    let current = "";
    for (const word of paragraph.split(/\s+/)) {
      const candidate = current ? `${current} ${word}` : word;
      if (font.widthOfTextAtSize(candidate, size) <= maxWidth) {
        current = candidate;
      } else {
        if (current) lines.push(current);
        current = word;
      }
    }
    if (current) lines.push(current);
  }
  return lines;
}

export async function buildApplicationPdf(
  input: ApplicationPdfInput,
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  doc.setTitle("Application under the Right to Information Act 2005");
  doc.setSubject(`RTI application to ${input.authorityName}`);
  doc.setProducer("RTI Sahayak, a concept prototype");

  const body = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const maxWidth = PAGE.width - MARGIN * 2;

  let page = doc.addPage([PAGE.width, PAGE.height]);
  let y = PAGE.height - MARGIN;

  const newPage = () => {
    page = doc.addPage([PAGE.width, PAGE.height]);
    y = PAGE.height - MARGIN;
  };

  const write = (
    text: string,
    { font = body, size = BODY_SIZE, gap = LINE, colour = rgb(0.1, 0.1, 0.1) } = {},
  ) => {
    for (const line of wrap(text, font, size, maxWidth)) {
      if (y < MARGIN + gap) newPage();
      if (line) {
        page.drawText(line, { x: MARGIN, y, size, font, color: colour });
      }
      y -= gap;
    }
  };

  write("APPLICATION UNDER THE RIGHT TO INFORMATION ACT, 2005", {
    font: bold,
    size: 14,
    gap: 22,
  });

  if (input.simulated) {
    write(
      "Generated by RTI Sahayak, a concept prototype. Not an official Government of India document and not submitted to any government system.",
      { size: 8.5, gap: 12, colour: rgb(0.42, 0.42, 0.42) },
    );
  }
  y -= 10;

  page.drawLine({
    start: { x: MARGIN, y },
    end: { x: PAGE.width - MARGIN, y },
    thickness: 0.75,
    color: rgb(0.8, 0.8, 0.8),
  });
  y -= 24;

  const field = (label: string, value: string) => {
    write(label.toUpperCase(), { font: bold, size: 8.5, gap: 12, colour: rgb(0.42, 0.42, 0.42) });
    write(value, { gap: LINE });
    y -= 6;
  };

  field("To", input.officer);
  field("Public authority", input.authorityName);
  if (input.ministry) field("Ministry", input.ministry);
  if (input.registrationNumber) {
    field("Registration number", input.registrationNumber);
  }
  field("Date", input.date);

  y -= 8;
  write("Information requested", { font: bold, size: 11.5, gap: 20 });
  write(input.body, { gap: LINE });

  y -= 14;
  write(
    "I am a citizen of India. No reason for this request is required under section 6(2) of the Act, and no identity document is enclosed.",
    { size: 9.5, gap: 14, colour: rgb(0.35, 0.35, 0.35) },
  );

  return doc.save();
}
